### ISSUE TITLE
Add Basic Auth Credentials

### ISSUE THREAD

**Issue by reredata3** [ligreman/king#37]
How to add credentials to my Consumer? 

I've looked through all the menus, but I can't find a way to add credentials for basic-auth. For now I am using existing api based on kong documentation.

Sorry for noobs question, maybe there is something i am missing, can you guys help me.

**Comment by ligreman** [comment]
Hello @reredata3.

In general for credential creation you must first create the plugin instance in your architecture (for example, to use JWT credentiasl you must first create a JWT plugin element and then in the Credentials -> Consumers page you will be able to create the credentials).

But I have not implemented the Basic Auth plugin in King yet. I take note and add it when I have some free time because it's very easy.

For now you must use the admin api directly.

Best regards.

**Comment by ligreman** [comment]
Kongs Basic Auth plugin doc:
https://docs.konghq.com/hub/kong-inc/basic-auth/

**Comment by ligreman** [comment]
Added Basic Auth plugin support to King v3.0.9
