### ISSUE TITLE
Connecting to private kong admin UI?

### ISSUE THREAD

**Issue by r4881t** [ligreman/king#41]
I am working with an environment where the Kong Admin UI is accessible within the same VPC. It's not exposed to internet. When I run King UI, and it asks me to enter the URL of Kong Admin, it always shows 404 which is understandable because it tries to connect from my browser.

Is there a way to solve this?

**Comment by ligreman** [comment]
King UI is made with Angular, which is based in Javascript and executed in the browser, as you explain.

What I would do in your case is:

- Use a server like apache/nginx (don't know if you are already doing this to serve King UI, you can use it for both purposes).
- The container of this apache server must be able to reach Kong's container. 
- The idea is to reach Kong's container using the apache server as a reverse proxy. With a ProxyPass configuration or similar, you can redirect requests made to an url and/or port in the apache server, to the Kong server.
- So, in King UI you will connect to the url+port of the apache server.

So, it will look like: Your browser -> connect to https://myapacheserver:8888 -> Apache will redirect all traffic in 8888 (or you can use paths instead of opening more ports) to Kong server port Admin.

I think this is the easiest way.
