### ISSUE TITLE
Search by capabilities?

### ISSUE THREAD

**Issue by jeremyjpj0916** [ligreman/king#48]
I see a filter by tags box, does that box allow searching by other field values(maybe broadly searches the JSON resources of each kong resource in question? )? Is there any way similar to konga where I can paste in search box route UUID or service UUID or route /uri/path/here or by Service name etc. or consumer name etc. to pull up a specific type of resource to edit when I am browsing existing resources?

Do consumer credentials jwt/oauth2.0 tokens also show up in the UI for CRUD actions? I think it says in docs they are supported so guessing yes.

**Comment by ligreman** [comment]
Right now the "tags filter box" in the Architect only filters by tags. It's not trivial to filter by other resource type, but it is possible to do. But I see this functionality as a "global search box" separate from the tags filter, where you could search "anything" among Kong resources and select to do one action on them. And maybe focus the graph on that selected resource.

The jwt and Oauth2.0 credentias already have full CRUD support in the ui.

**Comment by jeremyjpj0916** [comment]
Gotcha, yeah last thing in making king feature complete besides my other asks is a way to search at least by route URI or service name or consumer name fields and also be able to edit the plugins attached to either of them. As a gateway maintainer myself I need a way to search and filter on 3000+ proxies etc. which typically involves 3000 routes/service/plugins etc. Just filtering by resource type or dragging around on the generated map likely would not suffice in a large deployment like mine with how Konga enables filtering on routes/plugins/services/consumers etc.

**Comment by ligreman** [comment]
Yeah, I get your point of view and of course some "location" help is needed.

The idea os a global meta-searcher if a good one and I'll give it a think to see how can I implement it.

Meanwhile, in the current version of King you can search for specific resources (not filtering). In the menu you have "Architect" that is the graph view of the resources, but you also have the "Elements" menu, where you can view the resources by type in table format, and from there you can search for any element. The restriction here is only by type: you can search for one service, route, plugin... but from their respective tables. You don't have a global search field where you can search for anything. It is not so convenient but you can search for any resource, and view, edit or delete it. 

I made these two ways of resource visualization because the graph one is not always the best way (it's more visual but not so functional). Take a look at it.
